### ISSUE TITLE
Use GDB as a plugin for Neo4j Community edition

### ISSUE THREAD

**Issue by KienPM** [graphstackio/gdb#1]
Dear team,
How can I use GDB as a plugin for Neo4j Community edition?

**Comment by jmsuhy** [comment]
We plan on making the plugin available for the 4.3 version which should be out soon thanks to the community. You will just drop a single jar (uber jar with all dependencies) into your lib directory of your community distro.

When you run the maven build it already generates the jars, the plugin builder simply uses the maven shade plugin to combine them so you don’t have to drop in 20 jars.  It also has a utility to override the Community Entry Point.

**Comment by KienPM** [comment]
thank you!

**Comment by maheshkumargangula** [comment]
@jmsuhy - Is the plugin for the 4.3 version available? Can you please share the details to access it?
